-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*(100-DISCOUNT_RATE)/100*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE > "2022-11-00" AND START_DATE < "2022-12-00") AND C.CAR_TYPE IN ("세단", "SUV") AND P.DURATION_TYPE = "30일 이상"
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC