-- 코드를 입력하세요
SELECT HISTORY_ID, IFNULL(ROUND(DAILY_FEE*(100-DISCOUNT_RATE)/100*DURATION), ROUND(DAILY_FEE*DURATION)) AS FEE
FROM (SELECT HISTORY_ID, CAR_ID, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURATION, CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상' WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상' WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상' ELSE '' END AS DURATION_TYPE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ) AS RH
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON RH.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE AND RH.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC