-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT AS P
LEFT JOIN APPOINTMENT AS A
    ON P.PT_NO = A.PT_NO
LEFT JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_YMD LIKE "2022-04-13%" AND A.MCDP_CD = "CS" AND A.APNT_CNCL_YN = "N"
ORDER BY APNT_YMD